### ISSUE TITLE
The ability for autogenerated "|" in triple quote strings

### ISSUE THREAD

**Issue by omidb** [scalameta/metals-feature-requests#137]
**Is your feature request related to a problem? Please describe.**
In IntelliJ Idea after pressing ENTER in """ quote strings, it automatically adds "|" and line up the string with a ".stripmargines" at the end. it makes it very easy to work with """ strings.

**Describe the solution you'd like**
Adding a flag for that in the settings.

**Describe alternatives you've considered**
I think the same behaviour as in IntelliJ is a good start.

**Comment by tgodzik** [comment]
Thanks for reporting! The current way to achieve it is to add one `|` and then press enter, which should add `stripMargin`. It's important to note that `onTypeFormatting` must be first enabled in your editors of choice.

We could change the current behavior to also work without the additional `|`, but I feel like this is a good middle ground, so that people can explicitly say when they want `|` and `stripMargin.`  I am happy to discuss it though.

**Comment by omidb** [comment]
Thanks, I couldn't find any pointer to the option before. It would be cool to have these hints in docs that are easily accessible from VS Code or other editors.

**Comment by tgodzik** [comment]
> Thanks, I couldn't find any pointer to the option before. It would be cool to have these hints in docs that are easily accessible from VS Code or other editors.

You're right, it would be best to try and make it more obvious for people where to look for hints. Not 100 % sure how to make it so it doesn't become annoying. The best we can do is point at the docs, which might need some updating.

**Comment by omidb** [comment]
A cool official blogpost from Scala Center would be a good start.

**Comment by tgodzik** [comment]
We do post entries about the Metals releases on the `scalameta/metals` blog and the information about triple quote strings was even included in the recent release:

https://scalameta.org/metals/blog/2020/07/01/lithium.html
