### ISSUE TITLE
Support Intellij idea

### ISSUE THREAD

**Issue by Liyw979** [scalameta/metals-feature-requests#348]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

no

### Describe alternatives you've considered

Macro autocompletion in Intellij idea is not as good as metals, 
and Intellij idea has released support for LSP
https://blog.jetbrains.com/idea/2023/06/intellij-idea-2023-2-eap-7/

### Additional context

no

### Search terms

LSP, intellij idea

**Comment by tgodzik** [comment]
Thanks for reporting! I don't think we should provide LSP support for Intellij, maybe for Fleet, where there is no dedicated Scala support. I don't bar people from doing it themselves, but we will for sure not work on that at any point as there is already an existing plugin.

>Macro autocompletion in Intellij idea is not as good as metals,
and Intellij idea has released support for LSP

Instead of using full Metals underneath it would be better if Intellij used the presentation compiler interface, which got merged into the Scala 3 compiler. It could possibly be used as a fallback.

https://github.com/lampepfl/dotty/pull/17528
