### ISSUE TITLE
IntelliJ IDEA Metals plugin

### ISSUE THREAD

**Issue by scrous** [scalameta/metals-feature-requests#85]
**Describe the solution you'd like**
An installable IntelliJ plugin for Scala development that uses Metals. Alternatively, collaborate with the current IntelliJ Scala plugin team. Metals is way more responsive for code completion than the current Scala plugin for IntelliJ.

**Comment by tgodzik** [comment]
Hey, thanks for reporting! Unfortunately, Intellij doesn't provide a client for LSP and doesn't plan to do so from what I understand. Unless this changes we will not be able to provide a plugin for Intellij.

As for collaborating with the Scala plugin team, the completions used in Metals use the Scala presentation compiler and Intellij has partly reimplemented the compiler plus they are tightly coupled with Intellij IDEA itself. I don't believe this will be possible to reuse sensibly. 

You should most likely raise the issue about the responsiveness with the Scala Intellij team so that they are aware it's an issue. 

We do have contact with Jetbrains and collaborate on some project like Bloop or BSP, so I am sure that if they find it useful they will try to reuse some of our code and we will be happy to help.

**Comment by scrous** [comment]
I see there are some unofficial plugins that add LSP support to IntelliJ. https://github.com/gtache/intellij-lsp

**Comment by tgodzik** [comment]
> I see there are some unofficial plugins that add LSP support to IntelliJ. For example: https://github.com/gtache/intellij-lsp
> 
> Also listed here: https://langserver.org/

I think we need a proper support from Jetbrains for that, otherwise the experience will not be too good. That said, you should be able to use Metals with any client. more information [here](https://scalameta.org/metals/docs/editors/new-editor.html), but overall experience from Intellij Scala Plugin will be better currently for the IDEA platform.

If you are interested in using Metals, I would suggest using Visual Studio Code, which is most accessible and well supported currently. This will provide a very similar experience to Intellij and is itself much faster to startup. It also supports a number of additional LSP extensions that the Intellij Client might not be able to support in any near future.
