### ISSUE TITLE
Optionally attempt `git mv` when renaming a type 

### ISSUE THREAD

**Issue by Baccata** [scalameta/metals-feature-requests#90]
When I rename a type in vscode that matches the filename containing it, the file gets renamed as well. The problem is that moving a file AND making a change to it gets in the way of git's rename detection, which messes the history. 

I've had a look at a few of vscode's issues and the maintainers are reluctant to do anything at vscode level. 

The solution I'd like would like would be for metals to attempt a `git mv` on the file when renaming a type in this situation, when a git repository is detected. 

The alternative is calling upon `git mv` by hand before renaming the type. It's obviously slower.

**Comment by tgodzik** [comment]
Thanks for reporting! I agree that would be preferable that `git mv` is done on the renamed files, but the problem here is that Metals isn't the one doing the actual rename. We are just sending a request to VS Code to change the name of the file. Any solution that we might think of will be a bit hacky. This should be done in VS Code - I don't really understand why they are reluctant about it. Could you link some issues?

Possible solution I can think of would consist of two parts:
1. For most client we rename closed files in the background, so doing a `git mv` after rename would be preferable even if the client handles any open files
2. Run `git mv` after previously opened but renamed file shows up in a didOpen request

Problems:
- in VS Code we open all the files to make the rename preview work, so only step 2 would apply
- other clients might handle the rename with git mv already, so we would need specify it explicitly for each client

Overall, I think doing `1.` would really be useful for all clients, while `2.` should most likely be handled by the client.

**Comment by olafurpg** [comment]
Thank you for reporting! I agree with @tgodzik that this should ideally be handled by the client like VS Code. That's the best way to ensure a smooth user experience, especially around undoing a rename.

**Comment by Baccata** [comment]
> I agree with @tgodzik that this should ideally be handled by the client like VS Code

I do agree as well. Here's a couple issues showing reluctance on the vscode side : 

* https://github.com/Microsoft/vscode/issues/31380 
* https://github.com/microsoft/vscode/issues/53449

**Comment by gabro** [comment]
I actually share some of the concerns of the original issue: if you git add both the deleted and the new files, don’t they show up as a rename?
I’ve always thought of git mv as a convenience for using git add twice

**Comment by Baccata** [comment]
@gabro just ran a small experiment, it looks like it depends on how much of the file changes in addition to the rename. `git mv` does seem to be a convenience method, so there is strictly nothing metals could do even if vscode was indeed staging changes after a rename.

It's a case of PEBCAK, renaming should be committed in isolation I guess 

I'll close the issue, thanks anyway 😄
